services:
  disrecord:
    build:
      context: .
      target: final
    container_name: disrecord
    environment:
      - APP_ID=01234567890
      - BOT_TOKEN=abcdefghijklmnopqrstuvwxyz0123456789
      - LOG_LEVEL=trace # default
      - LOG_LEVEL_ALL=warn # default
    volumes:
      - ./recordings:/recordings
    restart: unless-stopped